package ist.com.sdk

/**
 * Algorithm output. Populated by the JNI through `setX` reflection calls.
 * Field names must remain stable for binary compatibility with the vendor .so.
 */
@Suppress("PropertyName")
class CurrentGlucose {
    @JvmField var glucoseId: Int = 0
    @JvmField var dayCount: Int = 0
    @JvmField var hour: Int = 0
    @JvmField var minute: Int = 0
    @JvmField var glu: Float = 0f
    @JvmField var gluMG: Int = 0
    @JvmField var ib: Float = 0f
    @JvmField var iw: Float = 0f
    @JvmField var ib2: Float = 0f
    @JvmField var iw2: Float = 0f
    @JvmField var ib3: Float = 0f
    @JvmField var iw3: Float = 0f
    @JvmField var t: Float = 0f
    @JvmField var bg: Float = 0f
    @JvmField var bgMG: Int = 0
    @JvmField var bgAdvice: Float = 0f
    @JvmField var bgMGAdvice: Int = 0
    @JvmField var bgCount: Int = 0
    @JvmField var bgICount: Int = 0
    @JvmField var trend: Int = 6
    @JvmField var errorCode: Int = 0
    @JvmField var warnCode: Int = 0
    @JvmField var calibrationStatus: Int = -1
    @JvmField var hypoglycemiaEarlyWarnMinutes: Int = 0
    @JvmField var hyperglycemiaEarlyWarnMinutes: Int = 0
    @JvmField var countdownDays: Int = 0
    @JvmField var countdownHours: Int = 0
    @JvmField var countdownMinutes: Int = 0
    @JvmField var k_BASE: Float = 0f
    @JvmField var k_AUTO: Float = 0f
    @JvmField var sensitivityCoefficient: Float = 0f
    @JvmField var iw4: Float = 0f
    @JvmField var iw30IIR: Float = 0f
    @JvmField var iw48IIR: Float = 0f
    @JvmField var iw48base: Float = 0f
    @JvmField var sdGlu: Float = 0f
    @JvmField var gluMG_AI: Int = 0
    @JvmField var glu_AI: Float = 0f
    @JvmField var beVoltage: Int = 0
    @JvmField var weVoltage: Int = 0
    @JvmField var reVoltage: Int = 0
    @JvmField var ceVoltage: Int = 0
    @JvmField var bVoltage: Int = 0
    @JvmField var algorithm: Int = 0
    @JvmField var endCycleCodeId: Int = 0
    @JvmField var bytes: ByteArray = ByteArray(0)

    fun setGlucoseId(v: Int) { glucoseId = v }
    fun setDayCount(v: Int) { dayCount = v }
    fun setHour(v: Int) { hour = v }
    fun setMinute(v: Int) { minute = v }
    fun setGlu(v: Float) { glu = v }
    fun setGluMG(v: Int) { gluMG = v }
    fun setIb(v: Float) { ib = v }
    fun setIw(v: Float) { iw = v }
    fun setIb2(v: Float) { ib2 = v }
    fun setIw2(v: Float) { iw2 = v }
    fun setIb3(v: Float) { ib3 = v }
    fun setIw3(v: Float) { iw3 = v }
    fun setT(v: Float) { t = v }
    fun setBG(v: Float) { bg = v }
    fun setBGMG(v: Int) { bgMG = v }
    fun setBG_ADVICE(v: Float) { bgAdvice = v }
    fun setBGMG_ADVICE(v: Int) { bgMGAdvice = v }
    fun setBGCount(v: Int) { bgCount = v }
    fun setBGICount(v: Int) { bgICount = v }
    fun setTrend(v: Int) { trend = v }
    fun setErrorCode(v: Int) { errorCode = v }
    fun setWarnCode(v: Int) { warnCode = v }
    fun setCalibrationStatus(v: Int) { calibrationStatus = v }
    fun setHypoglycemiaEarlyWarnMinutes(v: Int) { hypoglycemiaEarlyWarnMinutes = v }
    fun setHyperglycemiaEarlyWarnMinutes(v: Int) { hyperglycemiaEarlyWarnMinutes = v }
    fun setCountdownDays(v: Int) { countdownDays = v }
    fun setCountdownHours(v: Int) { countdownHours = v }
    fun setCountdownMinutes(v: Int) { countdownMinutes = v }
    fun setK_BASE(v: Float) { k_BASE = v }
    fun setK_AUTO(v: Float) { k_AUTO = v }
    fun setSensitivityCoefficient(v: Float) { sensitivityCoefficient = v }
    fun setIw4(v: Float) { iw4 = v }
    fun setIw30IIR(v: Float) { iw30IIR = v }
    fun setIw48IIR(v: Float) { iw48IIR = v }
    fun setIw48base(v: Float) { iw48base = v }
    fun setSD_GLU(v: Float) { sdGlu = v }
    fun setGluMG_AI(v: Int) { gluMG_AI = v }
    fun setGlu_AI(v: Float) { glu_AI = v }
    fun setBEVoltage(v: Int) { beVoltage = v }
    fun setWEVoltage(v: Int) { weVoltage = v }
    fun setREVoltage(v: Int) { reVoltage = v }
    fun setCEVoltage(v: Int) { ceVoltage = v }
    fun setBVoltage(v: Int) { bVoltage = v }
    fun setbVoltage(v: Int) { bVoltage = v }
    fun setAlgorithm(v: Int) { algorithm = v }
    fun setEndCycleCodeId(v: Int) { endCycleCodeId = v }
    fun setBytes(v: ByteArray) { bytes = v }

    fun getGlucoseId(): Int = glucoseId
    fun getDayCount(): Int = dayCount
    fun getHour(): Int = hour
    fun getMinute(): Int = minute
    fun getGlu(): Float = glu
    fun getGluMG(): Int = gluMG
    fun getIb(): Float = ib
    fun getIw(): Float = iw
    fun getIb2(): Float = ib2
    fun getIw2(): Float = iw2
    fun getIb3(): Float = ib3
    fun getIw3(): Float = iw3
    fun getT(): Float = t
    fun getBG(): Float = bg
    fun getBGMG(): Int = bgMG
    fun getBG_ADVICE(): Float = bgAdvice
    fun getBGMG_ADVICE(): Int = bgMGAdvice
    fun getBGCount(): Int = bgCount
    fun getBGICount(): Int = bgICount
    fun getTrend(): Int = trend
    fun getErrorCode(): Int = errorCode
    fun getWarnCode(): Int = warnCode
    fun getCalibrationStatus(): Int = calibrationStatus
    fun getHypoglycemiaEarlyWarnMinutes(): Int = hypoglycemiaEarlyWarnMinutes
    fun getHyperglycemiaEarlyWarnMinutes(): Int = hyperglycemiaEarlyWarnMinutes
    fun getCountdownDays(): Int = countdownDays
    fun getCountdownHours(): Int = countdownHours
    fun getCountdownMinutes(): Int = countdownMinutes
    fun getK_BASE(): Float = k_BASE
    fun getK_AUTO(): Float = k_AUTO
    fun getSensitivityCoefficient(): Float = sensitivityCoefficient
    fun getIw4(): Float = iw4
    fun getIw30IIR(): Float = iw30IIR
    fun getIw48IIR(): Float = iw48IIR
    fun getIw48base(): Float = iw48base
    fun getSD_GLU(): Float = sdGlu
    fun getGluMG_AI(): Int = gluMG_AI
    fun getGlu_AI(): Float = glu_AI
    fun getAlgorithm(): Int = algorithm
    fun getEndCycleCodeId(): Int = endCycleCodeId
    fun getBytes(): ByteArray = bytes
}
